### ISSUE TITLE
AssertionError: received no files

### ISSUE THREAD

**Issue by wangn123** [HealthML/self-supervised-3d-tasks#2]
thanks  for sharing such a great job，I have read you documentation for the config flags in README.MD，but I have some problems，when i run finetune.py/ exemple_2d.json on the  2d_brats, The error list is displayed as follows：
Traceback (most recent call last):
  File "finetune.py", line 4, in <module>
    main()
  File "/home/wn/self/self-supervised-3d-tasks-master/self_supervised_3d_tasks/finetune.py", line 402, in main
    init(run_complex_test, "test")
  File "/home/wn/self/self-supervised-3d-tasks-master/self_supervised_3d_tasks/utils/model_utils.py", line 67, in init
    f(**args)
  File "/home/wn/self/self-supervised-3d-tasks-master/self_supervised_3d_tasks/finetune.py", line 328, in run_complex_test
    gen_train, gen_val, x_test, y_test = data_loader.get_dataset(i, percentage)
  File "/home/wn/self/self-supervised-3d-tasks-master/self_supervised_3d_tasks/test_data_backend.py", line 240, in get_dataset
    val_split=self.val_split)
  File "/home/wn/self/self-supervised-3d-tasks-master/self_supervised_3d_tasks/data/make_data_generator.py", line 88, in make_generators
    **self.kwargs)
  File "/home/wn/self/self-supervised-3d-tasks-master/self_supervised_3d_tasks/data/make_data_generator.py", line 30, in get_data_generators_internal
    train_data_generator = data_generator(data_path, train, **train_data_generator_args)
  File "/home/wn/self/self-supervised-3d-tasks-master/self_supervised_3d_tasks/data/kaggle_retina_data.py", line 35, in __init__
    super().__init__(file_list, batch_size, shuffle, pre_proc_func)
  File "/home/wn/self/self-supervised-3d-tasks-master/self_supervised_3d_tasks/data/generator_base.py", line 35, in __init__
    assert len(file_list) > 0, "received no files"
AssertionError: received no files

I speculate that there is a problem with the .csv file. I have tried to write all the names of brats dataset or the path of the brats into the csv_file , but it does not work. Could you please give me a list of  the csv_file and csv_file_train specifically contents? or could you please tell me some way to slove the problem？ thanks a lot again.

**Comment by aihamtaleb** [comment]
Hi @wangn123 ,
Sorry for the late response. I believe you should check the documentation here: https://github.com/HealthML/self-supervised-3d-tasks 

The csv_file flag is only useful if you are training for classification, as opposed to segmentation. The task in brats is segmentation, so this flag is not needed to train on brats. In addition, brats is usually a 3D dataset, so you probably should consider training using the 3D versions of our algorithms. (using finetune/exemplar_3D.json). 
Also, when you use exemplar or any other algorithm, you should then feed the pretrained model using this algorithm by filling "model_checkpoint" flag. However, if you wish to train from scratch, check out the finetune/random_....json files.
